### 1. Setup - Importar librerías

In [1]:
import pandas as pd

### 2. Configuración

In [2]:
data_input = "../data/processed/germany.veterinarians.csv"
data_output = "../data/processed/germany.dashboard.csv"

columnas_categoricas = ["status of employment", "field of work", "federal state", "community size", "gender", "income"]

columnas_ERI = ["ERI_1","ERI_2","ERI_3","ERI_4","ERI_5","ERI_6","ERI_7","ERI_8","ERI_9","ERI_10"]
columnas_CBI = ["CBI_01","CBI_02","CBI_03","CBI_04","CBI_05","CBI_06"]
columnas_OTHERS = ["REDONDEAR","gender","status of employment","field of work","federal state","community size","income"]

### 3. Mapeo de valores

In [3]:
status_of_employment = {
    1: "Self-Employed",
    2: "Employed",
    3: "Unemployed by Choice",
    4: "Currently looking for a job",
    5: "Parental Leave",
    6: "Working in a non-veterinarian field",
    7: "Retired",
    8: "Medical Leave",
    9: "Other" # Translated for consistency
}

field_of_work = {
    1: "Small Animal Medicine",
    2: "Horses",
    3: "Farm Animals",
    4: "Mixed practice",
    5: "Food Industry",
    6: "Slaughterhouse",
    7: "R&D",
    8: "Industry Technical Service",
    9: "Industry Field Service",
    10: "Public Health",
    11: "Research",
    12: "University",
    13: "Zoo Animals",
    14: "Other",
    15: "Other"
}

federal_state = {
    1: "Baden-Wurttemberg",
    2: "Bavaria",
    3: "Berlin",
    4: "Brandenburg",
    5: "Bremen",
    6: "Hamburg",
    7: "Hessen",
    8: "Mecklenburg-Vorpommern",
    9: "Niedersachsen",
    10: "North Rhine-Westphalia",
    11: "Rheinland-Pfalz",
    12: "Saarland",
    13: "Saxony (Sachsen)",
    14: "Saxony-Anhalt",
    15: "Schleswig-Holstein",
    16: "Thuringia"
}

gender = {
    1: "Male",
    2: "Female"
}

community = {
    1: "5000 pop. aprox.",
    2: "20000 pop. aprox.",
    3: "50000 pop. aprox.",
    4: "100000 pop. aprox."
}

income = {
    1: "1. less than 1000 eur",
    2: "2. 1000 to 2000 eur",
    3: "3. 2000 to 3000 eur",
    4: "4. 3000 to 4000 eur",
    5: "5. 4000 to 5000 eur",
    6: "6. more than 5000 eur"
}

working_hours = {
    1: "0-20",
    2: "21-40",
    3: "41-60",
    4: "61-80",
    5: "81 or more"
}

eri_scale = {
    1: "Strongly disagree",
    2: "Disagree",
    3: "Agree",
    4: "Strongly agree"
}

cbi_scale = {
    100: "Always",
    75: "Often",
    50: "Sometimes",
    25: "Seldom",
    0: "Never"
}

cbi_score = {
    1: 100,
    2: 75,
    3: 50,
    4: 25,
    5: 0
}

### 4. Cargar los datos

In [4]:
# Cargar datos
print("-" * 50)
print("Cargando datos...")
print("-" * 50)

df = pd.read_csv(data_input)
print(f"Filas: {df.shape[0]}, Columnas: {df.shape[1]}")
print("-" * 50)
print("\nPrimeras 5 filas:")
display(df.head())

--------------------------------------------------
Cargando datos...
--------------------------------------------------
Filas: 3053, Columnas: 27
--------------------------------------------------

Primeras 5 filas:

,ERI_1,ERI_2,ERI_3,ERI_4,ERI_5,ERI_6,ERI_7,ERI_8,ERI_9,ERI_10,...,birth year,status of employment,field of work,federal state,community size,income,working_hours,age,CBI_SCORE,Burnout_Score
0,3,3,3,1,3,3,3,2,2,1,...,1986.0,9,12,2,2,1,60,40.0,33.3,0
1,2,2,2,3,3,2,1,3,3,3,...,1980.0,2,9,4,2,3,35,46.0,75.0,1
2,3,3,3,3,2,2,1,3,3,3,...,1989.0,2,9,4,1,3,42,37.0,37.5,0
3,3,4,4,1,2,2,2,2,2,3,...,1984.0,2,5,4,3,3,45,42.0,41.7,0
4,3,3,3,3,2,2,2,3,3,3,...,1978.0,2,2,4,4,2,40,48.0,95.8,1

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3053 entries, 0 to 3052
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ERI_1                 3053 non-null   int64
 1   ERI_2                 3053 non-null   int64
 2   ERI_3                 3053 non-null   int64
 3   ERI_4                 3053 non-null   int64
 4   ERI_5                 3053 non-null   int64
 5   ERI_6                 3053 non-null   int64
 6   ERI_7                 3053 non-null   int64
 7   ERI_8                 3053 non-null   int64
 8   ERI_9                 3053 non-null   int64
 9   ERI_10                3053 non-null   int64
 10  CBI_01                3053 non-null   int64
 11  CBI_02                3053 non-null   int64
 12  CBI_03                3053 non-null   int64
 13  CBI_04                3053 non-null   int64
 14  CBI_05                3053 non-null   int64
 15  CBI_06                3053 non-null   int64
 16  gender                3053 non-null   int64
 17  birth year            3053 non-null   float64
 18  status of employment  3053 non-null   int64
 19  field of work         3053 non-null   int64
 20  federal state         3053 non-null   int64
 21  community size        3053 non-null   int64
 22  income                3053 non-null   int64
 23  working_hours         3053 non-null   int64
 24  age                   3053 non-null   float64
 25  CBI_SCORE             3053 non-null   float64
 26  Burnout_Score         3053 non-null   int64
dtypes: float64(3), int64(24)
memory usage: 644.1 KB

### 5. Transformacion de datos para el dashboard

In [6]:
dashboard = df.copy()
dashboard["status of employment"] = dashboard["status of employment"].map(status_of_employment)
dashboard["field of work"] = dashboard["field of work"].map(field_of_work)
dashboard["federal state"] = dashboard["federal state"].map(federal_state)
dashboard["gender"] = dashboard["gender"].map(gender)
dashboard["community size"] = dashboard["community size"].map(community)
dashboard["income"] = dashboard["income"].map(income)
dashboard[columnas_ERI] = dashboard[columnas_ERI].replace(eri_scale)
dashboard[columnas_CBI] = dashboard[columnas_CBI].replace(cbi_scale)

In [7]:
dashboard.head(20)

,ERI_1,ERI_2,ERI_3,ERI_4,ERI_5,ERI_6,ERI_7,ERI_8,ERI_9,ERI_10,...,birth year,status of employment,field of work,federal state,community size,income,working_hours,age,CBI_SCORE,Burnout_Score
0,Agree,Agree,Agree,Strongly disagree,Agree,Agree,Agree,Disagree,Disagree,Strongly disagree,...,1986.0,Other,University,Bavaria,20000 pop. aprox.,1. less than 1000 eur,60,40.0,33.3,0
1,Disagree,Disagree,Disagree,Agree,Agree,Disagree,Strongly disagree,Agree,Agree,Agree,...,1980.0,Employed,Industry Field Service,Brandenburg,20000 pop. aprox.,3. 2000 to 3000 eur,35,46.0,75.0,1
2,Agree,Agree,Agree,Agree,Disagree,Disagree,Strongly disagree,Agree,Agree,Agree,...,1989.0,Employed,Industry Field Service,Brandenburg,5000 pop. aprox.,3. 2000 to 3000 eur,42,37.0,37.5,0
3,Agree,Strongly agree,Strongly agree,Strongly disagree,Disagree,Disagree,Disagree,Disagree,Disagree,Agree,...,1984.0,Employed,Food Industry,Brandenburg,50000 pop. aprox.,3. 2000 to 3000 eur,45,42.0,41.7,0
4,Agree,Agree,Agree,Agree,Disagree,Disagree,Disagree,Agree,Agree,Agree,...,1978.0,Employed,Horses,Brandenburg,100000 pop. aprox.,2. 1000 to 2000 eur,40,48.0,95.8,1
5,Agree,Agree,Agree,Strongly disagree,Strongly agree,Agree,Strongly agree,Strongly disagree,Disagree,Strongly disagree,...,1961.0,Employed,Industry Field Service,Brandenburg,20000 pop. aprox.,4. 3000 to 4000 eur,50,65.0,66.7,1
6,Disagree,Strongly agree,Disagree,Disagree,Agree,Disagree,Disagree,Disagree,Disagree,Disagree,...,1968.0,Employed,Zoo Animals,Mecklenburg-Vorpommern,20000 pop. aprox.,3. 2000 to 3000 eur,38,58.0,41.7,0
7,Agree,Agree,Agree,Agree,Agree,Disagree,Strongly disagree,Agree,Disagree,Agree,...,1966.0,Employed,Industry Field Service,Baden-Wurttemberg,20000 pop. aprox.,4. 3000 to 4000 eur,20,60.0,41.7,0
8,Agree,Agree,Agree,Disagree,Agree,Agree,Disagree,Disagree,Disagree,Agree,...,1970.0,Employed,Industry Field Service,Brandenburg,5000 pop. aprox.,4. 3000 to 4000 eur,40,56.0,37.5,0
9,Agree,Agree,Strongly agree,Agree,Disagree,Disagree,Strongly disagree,Agree,Agree,Disagree,...,1956.0,Other,Horses,Brandenburg,5000 pop. aprox.,1. less than 1000 eur,55,70.0,33.3,0
10,Agree,Strongly agree,Agree,Agree,Disagree,Disagree,Disagree,Strongly agree,Agree,Strongly agree,...,1970.0,Employed,Industry Field Service,Brandenburg,5000 pop. aprox.,4. 3000 to 4000 eur,40,56.0,54.2,1
11,Agree,Agree,Agree,Disagree,Strongly agree,Disagree,Strongly disagree,Disagree,Disagree,Agree,...,1958.0,Employed,Food Industry,Brandenburg,5000 pop. aprox.,3. 2000 to 3000 eur,44,68.0,54.2,1
12,Agree,Agree,Strongly agree,Disagree,Agree,Agree,Strongly disagree,Disagree,Disagree,Agree,...,1969.0,Employed,Other,Brandenburg,50000 pop. aprox.,3. 2000 to 3000 eur,50,57.0,58.3,1
13,Strongly agree,Strongly agree,Strongly agree,Disagree,Agree,Agree,Strongly disagree,Strongly disagree,Strongly disagree,Strongly disagree,...,1983.0,Employed,Small Animal Medicine,Saxony (Sachsen),100000 pop. aprox.,3. 2000 to 3000 eur,50,43.0,12.5,0
14,Strongly agree,Strongly agree,Strongly agree,Strongly disagree,Agree,Agree,Disagree,Strongly disagree,Disagree,Agree,...,1974.0,Employed,Slaughterhouse,Saxony (Sachsen),100000 pop. aprox.,5. 4000 to 5000 eur,50,52.0,41.7,0
15,Strongly agree,Strongly agree,Strongly agree,Strongly disagree,Strongly agree,Disagree,Disagree,Disagree,Disagree,Strongly disagree,...,1983.0,Employed,Small Animal Medicine,Saxony (Sachsen),100000 pop. aprox.,2. 1000 to 2000 eur,55,43.0,37.5,0
16,Strongly agree,Strongly agree,Agree,Disagree,Disagree,Disagree,Strongly disagree,Agree,Strongly agree,Strongly agree,...,1957.0,Employed,Research,Saxony (Sachsen),50000 pop. aprox.,6. more than 5000 eur,50,69.0,29.2,0
17,Disagree,Disagree,Agree,Agree,Strongly agree,Agree,Agree,Strongly agree,Strongly agree,Agree,...,1987.0,Employed,Slaughterhouse,Saxony (Sachsen),100000 pop. aprox.,2. 1000 to 2000 eur,20,39.0,41.7,0
18,Disagree,Agree,Disagree,Disagree,Agree,Agree,Disagree,Disagree,Agree,Disagree,...,1963.0,Employed,Industry Field Service,Saxony (Sachsen),5000 pop. aprox.,3. 2000 to 3000 eur,40,63.0,79.2,1
19,Strongly agree,Strongly agree,Strongly agree,Agree,Strongly agree,Agree,Strongly disagree,Agree,Disagree,Disagree,...,1963.0,Employed,Industry Field Service,Saxony (Sachsen),5000 pop. aprox.,4. 3000 to 4000 eur,45,63.0,37.5,0

In [8]:
dashboard.to_csv(data_output, index=False)